receivers:
  otlp:
    protocols:
      grpc:
      http:

extensions:
exporters:
  otlphttp:
    traces_endpoint: "jaeger.railway.internal:4317"
  debug/detailed:
    verbosity: detailed
  elasticsearch:
    endpoints: ["http://elasticsearch.railway.internal:9200"]
    logs_index: logs-otel
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/detailed, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/detailed]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug/detailed, elasticsearch]
